# 系统的 appCode 唯一标示
# 如果接入 权限系统 需要在权限系统中维护对应的 app
appCode: MISSILE

# 系统的标题
pageTitle: Missile数据化运营服务平台

# api前缀
# 为了支持透传功能，区分 ajax 请求和正常页面访问，如
# 页面访问 /papaya/app
# 接口请求 /papaya/api/app/query
# 由于是单页应用，使用 HTML5 history 模式，需要对页面请求使用 主页 渲染
apiPrefix: /api

# 基础路径
# 目前大量的系统是挂载在同一个域名下，使用不同的路径做区别，如
# loan.wacai.info/wups 权限系统
# loan.wacai.info/adanos 审批系统
baseURI: /missile

# 链接访问白名单
# 在鉴权中间件中会将以下地址添加到白名单
# 不需要添加 baseURI 和 apiPrefix，鉴权中间件会自动处理
authWhiteList:
  - /logout
  - /favicon.ico
  - /check_backend_active.html

# 后端 Java 服务接口地址
backendMap:
  development: http://localhost:9005/mock/
  test: http://missile-jiubao.tale.k2.test.wacai.info/missile/
  staging: http://api.stanlee.staging.wacai.info/missile/
  production: http://api.stanlee.wacai.info/missile/

# redis 服务器
redisMap:
  development:
    port: 6379
    host: 001.pub.redis.dev.wacai.info
  test:
    port: 6379
    host: 001.pub.redis.test.wacai.info
  staging:
    port: 6379
    host: 10.1.23.46
    # host: 10.1.23.47
  production:
    port: 6387
    host: 192.168.10.20

# 权限中心数据接口
authMap:
  development: http://localhost:9005/mock/auth
  test: http://auth-service.test.wacai.info/auth-service/auth
  staging: http://api.loan.wacai.info/auth-service/auth
  production: http://api.loan.wacai.info/auth-service/auth

server:
  port: 3000
  devPort : 9005
  debugPort: 7005

# cas登录链接
# casUrl: https://cas.wacai.com
# 快贷登录页
# casUrl: https://kuaidai-cas.wacai.info

# 外包配置，如果没有外包需求，请注释
# out:
#   # 外包cas登录链接
#   casUrl: https://loancs.wacai.com

#   # 对外开放的域名
#   domain: loancs.wacai.com
