extends: airbnb
parser: babel-eslint
env:
  es6: true
  browser: true
  node: true
  mocha: true
globals:
    $: true
    jQuery: true
    wx: true
    fis: true
    ReactDOM: true
    React: true
    df_alert: true
    location: true
    zhuge: true
    followId: true
    Swiper: true
rules: 
  semi:
    - error
    - never
  experimentalDecorators: false
  arrow-body-style: 0
  max-len: 0
  no-new: 0
  no-continue: 0
  global-require: 0
  no-console: 0
  guard-for-in: 0
  import/no-dynamic-require: 0
  no-use-before-define: 0
  no-underscore-dangle: 0
  no-restricted-syntax: 0
  no-class-assign: 0
  no-extra-boolean-cast: 0
  no-return-assign: 0
  no-nested-ternary: 0
  eol-last: 0
  linebreak-style: 0
  no-mixed-operators: 0
  no-bitwise: 0
  prefer-const: 0
  comma-dangle: 0
  no-trailing-spaces: 0
  object-curly-spacing: 0
  jsx-quotes: 0
  react/jsx-sort-props: 0
  react/jsx-space-before-closing: 0
  react/prefer-stateless-function: 0
  react/jsx-no-bind: 0
  react/jsx-first-prop-new-line: 0
  react/jsx-filename-extension: 0
  react/react-in-jsx-scope: 0
  react/no-multi-comp: 0
  react/no-array-index-key: 0
  react/jsx-curly-spacing: 2
  react/prop-types: 0
  react/require-default-props: 0
  react/self-closing-comp: 0
  react/no-string-refs: 0
  react/jsx-boolean-value: 0
  rect/sort-comp: 0
  react/jsx-tag-spacing: 0
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/label-has-for: 0
  jsx-a11y/no-noninteractive-element-interactions: 0
  no-prototype-builtins: 0
  class-methods-use-this: 0
  no-param-reassign: 0
  camelcase: 0
  no-shadow: 0
  no-unused-expressions: 0
  no-plusplus: 0
  no-empty-pattern: 0
  import/no-unresolved: 0
  import/extensions: 0
  prefer-destructuring: 0
  no-case-declarations: 0 
  no-debugger: 0
  quote-props: 
    - error 
    - consistent
  object-curly-newline:
    - error
    - ObjectExpression:
        multiline: true
        consistent: true
      ObjectPattern:
        multiline: true
