// 格式
// mock 地址 : 后端接口地址
// 两者一致可以不写

module.exports = {
  // cost
  // 获取费用信息
  'backend/cost/costQuery': '/backstage/promotion/cost_center/select',
  // 编辑费用信息
  'backend/cost/costSave': '/backstage/promotion/cost_center/edit',
  // 更新费用信息状态
  'backend/cost/costUpdate': '/backstage/promotion/cost_center/update_status',
  // business
  // 获取所有业务线
  'backend/business/businessQuery': '/backstage/common/biz/list_all',
  // 修改业务
  'backend/business/businessSave': '/backstage/common/biz/edit',
  // 新增业务
  'backend/business/businessAdd': '/backstage/common/biz/add',
  // system
  // 获取输出系统信息
  'backend/system/systemQuery': '/backstage/user_filter/direct_sys/select',
  // 编辑输出系统
  'backend/system/systemSave': '/backstage/user_filter/direct_sys/edit',
  // 新增输出系统
  'backend/system/systemAdd': '/backstage/user_filter/direct_sys/add',
  // 删除输出系统
  'backend/system/systemRemove': '/backstage/user_filter/direct_sys/delete',
  // info
  // 获取附加字段信息
  'backend/info/infoQuery': '/backstage/promotion/add_addition/select',
  // 新增附加字段信息
  'backend/info/infoAdd': '/backstage/promotion/add_addition/add',
  // 编辑附加字段信息
  'backend/info/infoSave': '/backstage/promotion/add_addition/edit',
  // 更新附加字段状态
  'backend/info/infoUpdate': '/backstage/promotion/add_addition/update_status',
  // compare
  // 获取动态比较值信息
  'backend/compare/compareQuery': '/backstage/user_filter/compare_element_menu/select',
  // 新增动态比较值
  'backend/compare/compareAdd': '/backstage/user_filter/compare_element_menu/add',
  // 删除动态比较值
  'backend/compare/compareRemove': '/backstage/user_filter/compare_element_menu/delete',
  // 编辑动态比较值
  'backend/compare/compareSave': '/backstage/user_filter/compare_element_menu/edit',
  // 编辑动态比较值组
  'backend/compare/addCompareSave': '/backstage/user_filter/compare_element/add_or_update',
  // 查询动态比较值组
  'backend/compare/addCompareQuery': '/backstage/user_filter/compare_element/select',
  // 删除删选指标
  'backend/compare/addCompareRemove': '/backstage/user_filter/compare_element/delete',
  // quota
  // 获取画像指标集列表信息
  'backend/quota/quotaQuery': '/backstage/user_filter/filter_metric_menu/select',
  // 新增画像指标集列表
  'backend/quota/quotaAdd': '/backstage/user_filter/filter_metric_menu/add',
  // 编辑画像指标集列表
  'backend/quota/quotaSave': '/backstage/user_filter/filter_metric_menu/edit',
  // 删除画像指标集列表
  'backend/quota/quotaRemove': '/backstage/user_filter/filter_metric_menu/menu/delete',
  // 删除画像指标集列表中是数据源
  'backend/quota/removeDataSource': '/backstage/user_filter/filter_metric_menu/table/delete',
  // 列出数据库列表接口
  'backend/quota/addQuotaQueryDataBase': '/backstage/user_filter/filter_metric/database_list',
  // 列出数据库对应数据表接口
  'backend/quota/addQuotaQueryTableId': '/backstage/user_filter/filter_metric/column_list',
  // 列出数据表对应数据字段接口
  'backend/quota/addQuotaQueryDbId': '/backstage/user_filter/filter_metric/table_list',
  // 画像指标添加接口
  'backend/quota/addQuotaSave': '/backstage/user_filter/filter_metric/add_or_update',
  // 用户筛选列表
  'user-filter/filterQuery': '/user_filter/list/search',
  // 用户筛选列表全部
  'user-filter/filterAllQuery': '/user_filter/list/all',
  // 用户筛选添加
  'user-filter/filterAdd': '/user_filter/create/sql/add',
  // 用户筛选编辑
  'user-filter/filterUpdate': '/user_filter/list/sql/edit',
  // 用户筛选添加/编辑时检查 SQL
  'user-filter/filterCheckSQL': '/user_filter/create/sql/check',
  // 用户筛选文件上传
  'user-filter/filterUploadTable': '/user_filter/create/file/add',
  // 用户筛选编辑获取数据
  'user-filter/filterGet': '/user_filter/list/detail',
   // 用户筛选文件上传编辑获取数据
  'user-filter/filterUploadGet': '/user_filter/list/detailWithPreview',
  // 用户筛选切换有效/无效
  'user-filter/filterStatus': '/user_filter/list/update_status',
  // 用户筛选复制
  'user-filter/filterCopy': '/user_filter/list/copy',
  // 用户筛选删除
  'user-filter/filterDel': '/user_filter/list/delete',
  // 营销活动列表
  'marketing-activity/list/query': '/promotion/activity/list/search',
  // 营销活动删除
  'marketing-activity/list/del': '/promotion/activity/list/delete_activity',
  // 营销活动切换有效/无效
  'marketing-activity/list/updateStatus': '/promotion/activity/list/update_status',
  // 营销活动切换详情
  'marketing-activity/list/detail': '/promotion/activity/list/detail_activity_user_group',
  // 福利信息列表
  'marketing-activity/welfare/query': '/activity/welfare/cost/list',
  // 福利信息获取附加字段
  'marketing-activity/welfare/additionByBiz': '/backstage/promotion/add_addition/list_by_biz',
  // 福利信息信息补全
  'marketing-activity/welfare/edit': '/activity/welfare/addition/edit',
  // 营销活动编辑活动信息时获取
  'marketing-activity/update/getInfo': '/promotion/activity/list/detail_activity_base_info',
  // 营销活动添加/编辑活动信息
  'marketing-activity/update/updateInfo': '/promotion/activity/add_or_update/base',
  // 营销活动按筛选画像添加用户组
  'marketing-activity/update/addProfile': '/promotion/activity/add/profile/user_group',
  // 营销活动按实时标签添加用户组
  'marketing-activity/update/addTag': '/promotion/activity/add/rule/user_group',
  // 营销活动编辑活动人群时获取
  'marketing-activity/update/getPeople': '/promotion/activity/list/detail_activity_base_info',
  // 营销活动按筛选画像编辑用户组
  'marketing-activity/update/editProfile': '/promotion/activity/edit/profile/user_group',
  // 营销活动按实时标签编辑用户组
  'marketing-activity/update/editTag': '/promotion/activity/edit/rule/user_group',
  // 营销活动获取标签列表
  'marketing-activity/rule/queryDefine': '/rule/profile/define',
  // 营销活动获取标签状态
  'marketing-activity/rule/queryStatus': '/rule/profile/status'
}
